baseURL = "https://accessible-minimalism.netlify.app/"
languageCode = "en-us"
title = "Accessible Minimalism Demo"
theme = "accessible-minimalism"
disableHugoGeneratorInject = true
enableRobotsTXT = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Features"
    url = "/features/"
    weight = 3
  [[menu.main]]
    name = "Sitemap"
    url = "/sitemap/"
    weight = 4

