[build]
publish = "public"
command = "export PATH=$PATH:$(pwd)/bin && hugo --gc --minify && find public -name '*.html' -type f -print -exec tidy -config tidy-config.txt -mq '{}' \;"

[context.production.environment]
HUGO_VERSION = "0.68.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
