[build]
publish = "public"
command = "export PATH=$PATH:$(pwd)/bin && hugo --gc && find public -name '*.html' -type f -print -exec tidy -mq -xml --wrap 0 --indent auto --indent-spaces 2 --quiet yes  '{}' \;"

[context.production.environment]
HUGO_VERSION = "0.68.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
