[build]
publish = "public"
command = "export PATH=$PATH:$(pwd)/bin && hugo --gc && find public -name '*.html' -type f -print -exec tidy -mq --tidy-mark no --wrap 0 --indent auto --indent-spaces 2 --quiet yes  '{}' \; && cp static/google75d7fb8a737d3bd4.html public/"

[context.production.environment]
HUGO_VERSION = "0.68.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
